<a href="https://colab.research.google.com/github/Fenix198811/Fenix198811/blob/main/PytorchStudyTensor2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Math Ops

In [2]:
import torch
import numpy as np

In [3]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

tensor([ 5, 12, 21, 32])

In [4]:
# Addition
tensor_a + tensor_b
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [5]:
# Subtraction
tensor_b - tensor_a
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [6]:
# Mutiplication
tensor_a * tensor_b
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [7]:
# Division
tensor_b / tensor_a
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [8]:
# Remainder
tensor_b % tensor_a
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [9]:
# Exponents / power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [14]:
# Reassignment
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)
print(tensor_a)

tensor([11, 14, 17, 20])
