<a href="https://colab.research.google.com/github/Fenix198811/Fenix198811/blob/main/PytorchStudyTensor1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Tensor Tests

In [2]:
import torch

tensor_2d = torch.randn(3,4)
print(tensor_2d)

tensor_3d = torch.randn(3,4,5)
print(tensor_3d)

tensor([[ 1.2139, -0.1825, -0.2528, -0.2290],
        [-2.1822,  0.7836, -0.2079, -0.3317],
        [ 0.5846, -0.9258, -1.5416,  1.9098]])
tensor([[[-0.4575,  1.1039, -1.2311, -1.2851,  0.8914],
         [ 0.1952,  0.8235, -0.0274,  1.1303, -0.2248],
         [-0.2503, -1.6917,  0.0516,  0.8665,  2.3058],
         [ 0.5913, -0.3522, -1.6390, -0.9362, -1.6152]],

        [[ 0.3430,  0.9391, -0.5505,  1.2215,  0.1789],
         [ 1.5276, -0.1680,  0.9462,  0.8432,  1.7019],
         [ 0.6627, -0.6698,  0.7308, -0.6381,  0.8038],
         [ 0.4316,  0.9912,  1.4473,  1.5581,  0.9303]],

        [[-1.1616,  1.1971,  0.4721, -0.8346, -0.1843],
         [-0.0249, -1.3957, -0.9641,  0.1196, -0.0146],
         [-0.1009, -2.5401,  0.7723, -1.3248, -0.1457],
         [-1.3005,  1.7827, -0.9298, -0.7277, -0.0661]]])


In [4]:
my_tensor = torch.arange(10)
print(my_tensor)

my_tensor = my_tensor.reshape(2,5)
print(my_tensor)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])


In [9]:
my_tensor2 = torch.arange(10)
print(my_tensor2)
my_tensor2 = my_tensor2.reshape(2, -1)
print(my_tensor2)

v = my_tensor2[:,1]
print(v)

v2 = my_tensor2[:,1:]
print(v2)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])
tensor([1, 6])
tensor([[1, 2, 3, 4],
        [6, 7, 8, 9]])
